// Generated by https://quicktype.io

export interface InfoPagina{
  titulo?:         string;
  email?:          string;
  nombre?:         string;
  pagina_autor?:   string;
  facebook?:       string;
  twitter?:        string;
  instagram?:      string;
  telegram?:       string;
  tumblr?:          string;
  equipo_trabajo?: any[];
}
